name: firebase_cloud_messaging_backend
description: Use fcm in your dart code.
# version: 1.0.0
# homepage: https://www.example.com
# author: Simon <simon@pdad.de>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  json_serializable: ^3.2.2
  googleapis_auth: ^0.2.10

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  build_runner: ^1.7.1

