name: firebase_cloud_messaging_backend
description: Use Firebase Cloud Messaging in your dart server code
author: lotrofans
version: 2.0.0
homepage: https://github.com/lotrofans/firebase_cloud_messaging_backend_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.6
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1
  googleapis_auth: ^1.4.1
  collection: ^1.18.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.24.3
  build_runner: ^2.3.3

